### ISSUE TITLE
action=PRECTION   Report an error

### ISSUE THREAD

**Issue by GuoHongXin999** [mangushev/mtad-gat#7]
![97Z8U3~ZT@{H3I 81W{V 77](https://user-images.githubusercontent.com/102945904/161490404-3deeb1e1-330f-4472-993e-3f8b459d57ec.png)
Traceback (most recent call last):
  File "F:/mtad-gat-master/training.py", line 379, in <module>
    main()
  File "F:/mtad-gat-master/training.py", line 267, in main
    scores = list(results)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 2919, in predict
    rendezvous.raise_errors()
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow_estimator\python\estimator\tpu\error_handling.py", line 131, in raise_errors
    six.reraise(typ, value, traceback)
  File "D:\Anaconda\envs\tf114\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 2913, in predict
    yield_single_examples=yield_single_examples):
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 637, in predict
    preds_evaluated = mon_sess.run(predictions)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\training\monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "D:\Anaconda\envs\tf114\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "D:\Anaconda\envs\tf114\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Key: input.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_221]]
  (1) Invalid argument: Key: input.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

Process finished with exit code 1
 
It works fine during training, but starts reporting errors at the file - inference_score.csv.generation step.
Do you have this problem?

**Comment by Killian-cressant** [comment]
Hi,

I have the same issue when I am doing the training, I guess it is an issue due to different version of tensorflow but cannot fix it yet, did you finally succeed ?

**Comment by GuoHongXin999** [comment]
Hi,




Yes, this code worked in the end. But I kinda forgot how I modified it. I used this version of tensorflow. tensorflow==1.14.0




At 2024-08-26 17:30:48, "Killian-cressant" ***@***.***> wrote:

Hi,

I have the same issue when I am doing the training, I guess it is an issue due to different version of tensorflow but cannot fix it yet, did you finally succeed ?
